### ISSUE TITLE
Installing as a dependency in an addon

### ISSUE THREAD

**Issue by lindyhopchris** [romulomachado/ember-cli-string-helpers#8]
## Version
String Helpers 1.2.0, Ember-CLI 2.12.2

## Steps to reproduce
In a new addon:

```
yarn add ember-cli-string-helpers
ember test
```

The Ember CLI documentation says to add dependencies of an addon that you want installed as into consuming applications as a dependency rather than a dev dependency:
https://ember-cli.com/extending/#addons-depending-on-other-addons

## Expected Behavior
Tests run successfully.

## Actual Behavior

Get the following error:

```
Cannot read property 'project' of undefined
TypeError: Cannot read property 'project' of undefined
    at Class.included ([my-addon]/node_modules/ember-cli-string-helpers/index.js:16:26)
    at Class.superWrapper [as included] ([my-addon]/node_modules/core-object/lib/assign-properties.js:34:20)
    at addons.map.addon ([my-addon]/node_modules/ember-cli/lib/models/addon.js:363:34)
    at Array.map (native)
    at Class.eachAddonInvoke ([my-addon]/node_modules/ember-cli/lib/models/addon.js:361:24)
    at Class.included ([my-addon]/node_modules/ember-cli/lib/models/addon.js:592:10)
    at Class.superWrapper [as included] ([my-addon]/node_modules/core-object/lib/assign-properties.js:34:20)
    at EmberAddon.<anonymous> ([my-addon]/node_modules/ember-cli/lib/broccoli/ember-app.js:500:15)
    at Array.filter (native)
    at EmberAddon.EmberApp._notifyAddonIncluded ([my-addon]/node_modules/ember-cli/lib/broccoli/ember-app.js:495:45)
    at EmberAddon.EmberApp [as appConstructor] ([my-addon]/node_modules/ember-cli/lib/broccoli/ember-app.js:140:8)
    at new EmberAddon ([my-addon]/node_modules/ember-cli/lib/broccoli/ember-addon.js:32:8)
    at module.exports ([my-addon]/ember-cli-build.js:5:13)
    at Builder.setupBroccoliBuilder ([my-addon]/node_modules/ember-cli/lib/models/builder.js:54:19)
    at new Builder ([my-addon]/node_modules/ember-cli/lib/models/builder.js:33:10)
    at BuildTask.run ([my-addon]/node_modules/ember-cli/lib/tasks/build.js:15:19)
```

**Comment by lindyhopchris** [comment]
I also see that the Ember CLI docs talk about adding addons via a blueprint too. Not sure when I'm supposed to use one approach or the other, so admit that maybe the above error might be caused by my ignorance!!

**Comment by romulomachado** [comment]
Hi @lindyhopchris, thanks for the bug report! 

I just pushed https://github.com/romulomachado/ember-cli-string-helpers/commit/1f7838f702a9d394f184cdd9c6dd9b5dd1a9f23f which fixes it. Also, `1.2.1` is available on npm, please update to it and let me know if everything's working for you.
